elasticsearch_helper_content.index.*:
  type: config_entity
  label: 'Elasticsearch content index config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    index_name:
      type: string
      label: 'Index name'
    entity_type:
      type: string
      label: 'Entity type'
    bundle:
      type: string
      label: 'Bundle'
    multilingual:
      type: boolean
      label: 'Option to add multilingual support'
    index_unpublished:
      type: integer
      label: 'Option to publish unpublished content'
    normalizer:
      type: string
      label: 'Entity normalizer'
    normalizer_configuration:
      type: sequence
      label: 'Entity normalizer configuration'
    third_party_settings:
      type: sequence
      label: 'Third party settings'
      sequence:
        type: elasticsearch_helper_content.index.third_party.[%key]
